# Generated by Django 5.0.4 on 2024-06-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'permissions': [('activate_comment', 'Can activate comment'), ('deactivate_comment', 'Can deactivate comment')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'permissions': [('publish_post', 'Can publish post')]},
        ),
    ]
