# Generated by Django 5.0.4 on 2024-06-17 09:24

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_cover_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image_2',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Cover Image'),
        ),
    ]
