# Generated by Django 5.0.4 on 2024-06-17 10:35

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_cover_image_2'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_image_2',
        ),

    ]
