# Generated by Django 5.0.4 on 2024-06-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_cover_image_2_alter_post_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_image',
        ),
    ]
