# Generated by Django 5.0.4 on 2024-06-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_cover_image_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_image_3',
            new_name='cover_image',
        ),
    ]
