# Generated by Django 5.0.4 on 2024-06-18 00:07


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_cover_image_3_post_cover_image'),
    ]

    operations = [

    ]
