# Generated by Django 5.0.4 on 2024-06-18 00:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_content2'),
    ]

    operations = [

    ]
