# Generated by Django 5.0.4 on 2024-06-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_content2'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='post',
        #     name='content2',
        # ),
    ]
