# Generated by Django 5.0.4 on 2024-06-18 00:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
